os: linux
dist: xenial
language: generic
sudo: required
before_install:
 - sudo apt-get install -y quilt qemu-user-static debootstrap bsdtar

script:
 - ./build-docker.sh
 
deploy:
  provider: releases
  file_glob: true
  file: "deploy/*.zip"
  skip_cleanup: true
  draft: true
  overwrite: true
  true:
    all_branches: true
  api_key:
    secure:  "c9uB2vW9xmHBkrfBgsZLw1KNV/NoE7ihK+ExnJbYTf2wmaiYJZr2WSwFIe0cRywO355++gDtHS7hCiS8Q7LPVDVbhOxCevjPDN5cpsuC0S8FyjDoJRO59cVaTPhWfEskyWLTKSfJi+l1Lc0+AtnPDTE3JTWGh2oQJeHZKErhvwNVGLgmtdY4MDCPi3/562ZjpujpmoxSfhCFFeVJGuWq2KGvlruV26bVEdiNdQP+9ERzUMEs7C3BKHWgBBOnwy0/pyFjBFkaaHc+1a3WXGjCEkZbK7Zca49NRHWRzsPRbZ2IoLfiM3W0zXZTzlz8pyrFAsOFIVSnsc03URZytZDIlg7TgrSd2SNK1YMevxfDktcwoDTF6TGSTB27VoFKxbOXxEy83BPbcG6ktxPq0OSgujUnKjtxzwSgaMIp0nhiQ+X0P0tuixTAU+Kp4dbLiA/H6MrxMSEUCFj4UsJzcSr3mD7mgvYk4OsbMkhyiztdad1CtUuiul8tCt/aNW8/nvXeaGjGNGD1p0KuOzE4aKFto0/fcCtn2EYMYDXGDz22GahKiL5tOiEol2wrcD1Bkku8oyr+kr/7jy/mUcPriLUzbBeDhXhRTwXOLKrdkOYZ+qTmn/AR1HveYwp3oMCPLr5S5QziGNQmeCInO7LXzlfEqUuOlZWX+nUwv39b8FixiMk="

notifications:
  slack: revolution-robotics:sXlaetqFuXuT3Vr4atwogEdK
